version: 2.1

orbs:
  coding-standard: ostrolucky/php-coding-standard@0.1.10

executors:
  php:
    docker:
      - image: circleci/php:cli-node-browsers
  php71:
    docker:
      - image: circleci/php:7.1-cli-jessie-node-browsers-legacy

commands:
  composer:
    parameters:
      extra:
        type: string
        default: ''
    steps:
      - run: composer update -n --no-progress --prefer-dist << parameters.extra >>
jobs:
  test_71:
    executor: php71
    steps: &steps
      - checkout
      - composer:
          extra: $COMPOSER_EXTRA
      - run: vendor/bin/phpunit --log-junit=/tmp/test_results/phpunit/test_result.xml
      - store_test_results:
          path: /tmp/test_results
  test_latest_php:
    executor: php
    steps: *steps
  test_lowest:
    executor: php71
    environment:
      COMPOSER_EXTRA: --prefer-lowest
    steps: *steps

workflows:
  version: 2
  main:
    jobs:
      - coding-standard/default
      - test_71
      - test_lowest
      - test_latest_php