version: 2.1

orbs:
  coding-standard: ostrolucky/php-coding-standard@0.1.5

executors:
  php71:
    docker:
      - image: circleci/php:7.1-cli-jessie-node-browsers-legacy

commands:
  composer:
    parameters:
      extra:
        type: string
        default: ''
    steps:
      - run: composer update -n --no-progress --prefer-dist << parameters.extra >>
jobs:
  test_71:
    executor: php71
    steps:
      - checkout
      - composer
      - run: vendor/bin/phpunit tests
  test_lowest:
    executor: php71
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}
      - composer:
          extra: --prefer-lowest
      - save_cache:
          key: composer-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: vendor/bin/phpunit tests

workflows:
  version: 2
  main:
    jobs:
      - coding-standard/default
      - test_71
      - test_lowest